baseURL = "http://example.org/"
languageCode = "fr-fr"
title = "Célixirs"
theme = "landing"
canonifyUrls = "true"

[params]

  name = "Celine Fronton"
  description = "Celixirs offre des services de bien être et d'accompagnement de la Femme en épuisement maternel"
  shareImage = "images/social.jpg"
  twitterHandle = "celixirs"

  favicon = "favicon.ico"

[[params.social]]
    title = "email"
    icon = "envelope"
    url = "mailto:celixirs@gmail.com"
[[params.social]]
    title = "twitter"
    icon = "twitter"
    url = "https://twitter.com/celixirs"
[[params.social]]
    title = "facebook"
    icon = "facebook"
    url = "http://facebook.com/celixirs"
