baseURL = "http://example.org/"
languageCode = "fr-fr"
title = "Célixirs"
theme = "split"

[params]

  name = "Celine Fronton"
  description = "Celixirs offre des services de bien être et d'accompagnement de la Femme en épuisement maternel"
  shareImage = "images/social.jpg"
  twitterHandle = "celixirs"

  favicon = "favicon.ico"

  # Section - Content
  [params.content]

    name = "Céline Fronton"
    tagline = "Maman. Femme. Accordée."
    bio = "Donec at libero id lectus porta dapibus eu in nibh. Cras id mauris sapien. Fusce viverra [luctus urna](#) ac rutrum. Duis semper elit eu mi facilisis eleifend. Donec semper, [ipsum in](#) malesuada congue, [purus sem](#) ullamcorper massa, sit amet lacinia nibh enim sed massa."

  [params.visual]
  
    [params.visual.image]
      enable = true
      file = "images/celine-fronton.jpg"
      position = "center center"
    
    [params.visual.video]
      enable = true
  
  # Links
  #
  # Links List #1
  [[params.links]]
    [params.links.list1]
      heading = "Renseignements"

      [[params.links.list1.link]]
        text = "Votre accompagnement"
        url = "#"

      [[params.links.list1.link]]
        text = "Leurs témoignages"
        url = "#"

      [[params.links.list1.link]]
        text = "Mon Blog"
        url = "#"

  # Links List #2
  [[params.links]]
    [params.links.list2]
      heading = "Accompagnement"

      [[params.links.list2.link]]
        text = "Prénatal"
        url = "#"

      [[params.links.list2.link]]
        text = "S'accorder"
        url = "#"

      [[params.links.list2.link]]
        text = "Personnalisé"
        url = "#"

  # Links List #3
  [[params.links]]
    [params.links.list3]
      heading = "Réseau"

      [[params.links.list3.link]]
        text = "Facebook"
        url = "#"

      [[params.links.list3.link]]
        text = "Instagram"
        url = "#"

      [[params.links.list3.link]]
        text = "Pinterest"
        url = "#"
